name: flamingo_generator
description: Automatically generate code for converting flamingo JSON by annotating Dart classes.
version: 0.9.0-nullsafety.0
repository: https://github.com/hukusuke1007/flamingo

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  analyzer: '>=0.40.4 <1.0.0'
  build: '>=0.12.6 <2.0.0'
  meta: '>=1.2.0 <2.0.0'
  source_gen: ^0.9.0
  flamingo_annotation: ^0.5.0-nullsafety.0

dev_dependencies:
  test: ^1.16.0-nullsafety.13
  build_test:
