name: flamingo_generator
description: Automatically generate code for converting flamingo JSON by annotating Dart classes.
version: 1.0.0
repository: https://github.com/hukusuke1007/flamingo

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  build: ^2.3.1
  meta: ^1.7.0
  source_gen: ^1.2.3
  flamingo_annotation: 1.0.0

dev_dependencies:
  test:
  build_test: