name: flamingo_example
description: Demonstrates how to use the flamingo plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  path_provider:
  pull_to_refresh_flutter3: ^2.0.1
  flutter_slidable:

  flamingo:
    path: ../
  flamingo_annotation: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:

  flamingo_generator:
    path: ../../flamingo_generator/

  test:

flutter:
  uses-material-design: true
  assets:
    - assets/
